### ISSUE TITLE
Outdated infos for addons, e.g. LiveReload

### ISSUE THREAD

**Issue by gerdneuman** [cpeterso/arewee10syet#10]
My issue is specific issue is the following: LiveReload is shown as supported at https://www.arewee10syet.com/ although it is not: https://bugzilla.mozilla.org/show_bug.cgi?id=1172415 (ticket has been reopened).

This surfaces our greater issue:
1. Currently once confirmed to work addon cannot be reset to being broken on www.arewee10syet.com
2. There is no contact address (mail or whatever) at www.arewee10syet.com - took me ages to find this here
3. Also no "fork me on github" or link to github to find this repo

In case the data from www.arewee10syet.com are used, e.g. by users or by qualifying addons for the earlier e10s enabling process, it would be nice if it would be able to update its data.

**Comment by cpeterso** [comment]
Thanks. I updated the website so the LiveReload entry links to the correct Bugzilla bug number. The website can now see that the LiveReload bug is still open and the add-on is not e10s compatible.

If an add-on's status on the website is incorrect, the best way to raise the issue is to comment in the add-on's Bugzilla bug.

https://bugzilla.mozilla.org/show_bug.cgi?id=1172415
